version: "3"

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_ARGS="--requirepass redis-stack"
