FROM node:18-alpine

ARG USERNAME
ARG port=3000

# Create a new user inside the container
RUN adduser --system ${USERNAME}

# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat git openssh-client
WORKDIR /app

RUN yarn global add pnpm
RUN chown -R ${USERNAME}: /app
USER ${USERNAME}

COPY entrypoint.sh /

ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE ${port}
ENV PORT ${port}
# set hostname to localhost
ENV HOSTNAME "0.0.0.0"

ENTRYPOINT ["/entrypoint.sh"]
